name: Audit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  audit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.24.x

      - name: Verify Dependencies
        run: go mod verify

      - name: Run Go Build
        run: go build -v ./...

      - name: Run Go Vet
        run: go vet ./...

      - name: Run Staticcheck
        run: |-
          go install honnef.co/go/tools/cmd/staticcheck@latest \
          && staticcheck ./...

      - name: Run Go Tests
        run: go test -race ./...
